Comment	CommentID	int
Comment	PostID	int
Comment	UserID	int
Comment	Content	text
Comment	CreatedAt	datetime
Comment	UpdatedAt	datetime
Crop	CropID	int
Crop	UserID	int
Crop	CropName	varchar
Crop	Variety	varchar
Crop	PlantedDate	date
Crop	ExpectedHarvestDate	date
Crop	Status	varchar
FarmingDiary	FarmingDiaryID	int
FarmingDiary	UserID	int
FarmingDiary	Date	date
FarmingDiary	ActivityType	varchar
FarmingDiary	Content	text
FarmingDiary	PhotoURL	varchar
FarmingDiary	CreatedAt	datetime
PaymentMethod	PaymentMethodID	int
PaymentMethod	UserID	int
PaymentMethod	CardNumber	varchar
PaymentMethod	ExpiryDate	date
PaymentMethod	CVC	varchar
Report	ReportID	int
Report	ReporterUserID	int
Report	ReportType	varchar
Report	TargetID	int
Report	Reason	text
Report	ReportedAt	datetime
Report	Status	varchar
Review	ReviewID	int
Review	OrderItemID	int
Review	UserID	int
Review	Rating	int
Review	Content	text
Review	CreatedAt	datetime
User	UserID	int
User	Name	varchar
User	Email	varchar
User	Password	varchar
User	PhoneNumber	varchar
User	Address	varchar
User	IsAdmin	tinyint
User	CreatedAt	datetime