spring.application.name=samyang

# Server configuration
server.address=localhost
server.port=8080

# JSP View Resolver configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# MySQL Database configuration
spring.datasource.url='bcl3tdeivjaxna8ymyni-mysql.services.clever-cloud.com'
spring.datasource.username='upx0uarcany9dr68'
spring.datasource.password='bcl3tdeivjaxna8ymyni'
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# DevTools configuration for hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources,src/main/webapp
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400