# Spring Boot Application Configuration for Samyang Agricultural Platform
# TODO: [학습포인트] 프로덕션 환경에서는 application-prod.yml 등으로 환경별 설정 분리 권장

server:
  port: 8080

spring:
  application:
    name: 'samyang'
  
  # 데이터베이스 연결 설정
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.47.105.223/samyang?characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      pool-name: Samyang-Pool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
   
  # JSP 뷰 설정
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  
  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/dev/samyang/upload
   
# MyBatis 설정
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.farm404.samyang.dto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true              # 2차 캐시 활성화
    lazy-loading-enabled: true       # 지연 로딩 활성화
    aggressive-lazy-loading: false   # 필요한 경우에만 로딩
    default-executor-type: REUSE     # PreparedStatement 재사용
    default-statement-timeout: 30    # 쿼리 타임아웃 30초
