#spring.application.name=firstProject
#spring.application.datasource.dirve-class=com.mysql.cj.jdbc.Driver
#properies 방식


#yml 방식
#url 뒤에 붙는 ? 는 매개변수
spring:
 application:
#프로젝트명
  name: 'samyang'
  #접속할 데이터베이스 설정
 datasource: 
  dirver-class-name : com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://34.47.105.223/farm404?charsetEncoding=utf-8
  username: root
  password: 6VNS*Z$ARf~j17e=
   
 mvc:
  view:
   prefix: /views/
   suffix: .jsp
   
mybatis:
 mapper-locations: classpath:/mapper/*.xml

  
  
